import type { GetServerSideProps } from 'next';
import Head from 'next/head'
import React, { useState } from 'react';
import { fetchClient } from '@/utils/fetchclient';

interface Props {
  content: string;
}

export default function Home({ content }: Props) {
  const [chatContent, setChatContent] = useState("");

  const onChangeChat = (e: React.ChangeEvent<HTMLInputElement>) => {
    setChatContent(e.target.value);
  };

  const onSendChat = () => {
    chatContent;
  };

  return (
    <>
      <Head>
        <title>smdk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <input type="text" onChange={onChangeChat}></input>
        <button onClick={onSendChat}>보내기</button>
        <div>{ content }</div>
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  const { data } = await fetchClient.get<Props>('/test');

  return {
    props: {
      content: data.content,
    },
  };
};