import type { GetServerSideProps } from 'next';
import Head from 'next/head'
import React, { useState } from 'react';
import axios from "axios";

interface Props {
  data: string;
}

export default function Home({ data }: Props) {
  const [chatContent, setChatContent] = useState("");

  const onChangeChat = (e: React.ChangeEvent<HTMLInputElement>) => {
    setChatContent(e.target.value);
  };

  const onSendChat = () => {
    chatContent;
  };
  console.log(typeof window, 22);

  return (
    <>
      <Head>
        <title>smdk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <input type="text" onChange={onChangeChat}></input>
        <button onClick={onSendChat}>보내기</button>
        <div>{ data }</div>
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { data } = await axios.get("http://localhost:3000/api/hello");
  console.log(typeof window, 11);

  return {
    props: {
      data: data.name,
    },
  };
};