import Head from 'next/head';
import React from 'react';
import { Center, Input, Stack, Container, Box, HStack, Text, Heading } from '@chakra-ui/react';
import { MAIN_COLOR } from '@/theme';

export default function Index() {
  const heartSize = 21;

  return (
    <>
      <Head>
        <title>smdk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preload" href="fonts/NotoSansKR-Light.woff2" as="font" type="font/woff2" crossOrigin="anonymous" />
        <link rel="preload" href="fonts/Inter-Light.woff2" as="font" type="font/woff2" crossOrigin="anonymous" />
      </Head>
      <main>
        <Box w="100vw" h="100vh">
          <Center>
            <HStack>
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width={heartSize}
                height={heartSize}
                fill="currentColor"
                viewBox="0 0 16 16"
              >
                <path fill={MAIN_COLOR} d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z" />
              </svg>
              <Heading as="h1" size="2xl">
                smdk
              </Heading>
            </HStack>
          </Center>
          <Center>
            <Stack spacing={3} w="80%">
              <Input variant="flushed" placeholder="아이디" focusBorderColor="primary" />
              <Input variant="flushed" placeholder="비밀번호" type="password" focusBorderColor="primary" />
            </Stack>
          </Center>
        </Box>
      </main>
    </>
  );
}
